### ISSUE TITLE
Cloud not refer BMSPushClient#didReciveBMSPushNotification

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [ibm-bluemix-mobile-services/bms-samples-swift-hellopush#27]
Hi, team.

I cloned this sample but I could not refer BMSPushClient#didReciveBMSPushNotification.

My Podfile is here(same as sample).
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloPush' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BMSPush'
  pod 'BMSCore'

  # Pods for HelloPush

end
```
This Podfile seems to get the latest version.

"pod install" result is here.
```
Analyzing dependencies
Downloading dependencies
Using BMSAnalyticsAPI (2.2.3)
Using BMSCore (2.3.5)
Using BMSPush (3.2.7)
Generating Pods project
Integrating client project
Sending stats
```

It looks that I cloud not download the latest version(3.3.2).
And, BMSPushClient#didReciveBMSPushNotification seems to be implemented only on the latest version.

Is not the latest version still on the pod repository?

**Comment by AnanthaKrish** [comment]
@Daiki-Kawanuma The problem is with your local cocoa pods cache. Please do any of this 
```
pod install --repo-update
```
OR 

```
pod repo update
pod install
```

**Comment by Daiki-Kawanuma** [comment]
@AnanthaKrish Thank you for your prompt reply.

I did "pod install --repo-update" but old version were still installed.
```
$ pod install --repo-update --verbose
  Preparing

Updating local specs repositories

Setting up CocoaPods master repo

Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)

~~~

Comparing resolved specification to the sandbox manifest
  - BMSAnalyticsAPI
  - BMSCore
  - BMSPush

Downloading dependencies

-> Using BMSAnalyticsAPI (2.2.3)

-> Using BMSCore (2.3.5)

-> Using BMSPush (3.2.7)
  - Running pre install hooks

~~~

Sending stats
      - BMSAnalyticsAPI, 2.2.3
      - BMSCore, 2.3.5
      - BMSPush, 3.2.7

-> Pod installation complete! There are 2 dependencies from the Podfile and 3 total pods installed.
```

Do my local machine have any problem?

**Comment by AnanthaKrish** [comment]
@Daiki-Kawanuma Try doing a `pod update` .If thats not fixing the issue then try to uninstall the cocoa pods completely and install it again .  Yeah , its a local machine issue . 

I am able to get the latest pods for the push sample 

<img width="567" alt="screenshot 2018-08-08 at 11 57 18 am" src="https://user-images.githubusercontent.com/16939018/43820002-87dd3e70-9b02-11e8-94d3-1b2203549931.png">

**Comment by Daiki-Kawanuma** [comment]
@AnanthaKrish "$ pod update" works well!! I cloud install BMSPush 3.3.2.

I'm very thank you for your helping and I'm sorry for the inconvenience to you because of my local machine.
