### ISSUE TITLE
Value of type 'BMSPushClient' has no member application

### ISSUE THREAD

**Issue by asoare** [ibm-bluemix-mobile-services/bms-samples-swift-hellopush#6]
Hello,

I get this error, here is the lines where it happens:
Value of type 'BMSPushClient' has no member application

let push = BMSPushClient.sharedInstance
push.application(UIApplication.sharedApplication(), didReceiveRemoteNotification: userInfo)

**Comment by AnanthaKrish** [comment]
Please Use the latest sample. Thank you
